# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Circular concentration
#'
#' Computes the von Mises concentration parameter κ of a vector
#' of radians.
#' @param theta Numeric vector of radians.
#' @return The maximum likelihood estimate of κ.
#' @export
WH_rad_kappa <- function(theta) {
    .Call(`_WHcircular_WH_rad_kappa`, theta)
}

#' Circular mean
#'
#' Computes the circular mean of a vector of radians.
#' @param theta Numeric vector of radians.
#' @return The circular mean in radians.
#' @examples
#' y <- c("01:00","01:15","01:30","01:45","02:00",
#'        "23:00","23:15","23:30","23:45","00:00")
#' X <- c(rep(0, 5), rep(1, 5))
#' theta <- WH_HHMM_to_rad(y)
#' print(WH_rad_to_HHMM(WH_rad_sd(theta)))
#' @export
WH_rad_mean <- function(theta) {
    .Call(`_WHcircular_WH_rad_mean`, theta)
}

#' Circular resultant vector
#'
#' Computes the circular resultant vector in polar coordinates
#' from a vector of radians. If the resultant length is
#' smaller than \code{DBL_EPSILON}, the mean direction is set to \code{NaN}.
#' @param theta Numeric vector of radians.
#' @return A numeric vector of 2 elements:
#' \itemize{
#'   \item Mean direction in radians
#'   \item Resultant length
#' }
#' @export
WH_rad_resultant <- function(theta) {
    .Call(`_WHcircular_WH_rad_resultant`, theta)
}

#' Circular ANOVA
#'
#' One-way analysis of variance for circular data in radians using the
#' Cordeiro–Paula–Botter¹ likelihood-ratio test.
#' @param theta Numeric vector of radians.
#' @param group Integer vector of group identifiers.
#' @return \emph{P}-value of the test statistic.
#' @references
#' 1. Cordeiro, G.M., Paula, G.A. and Botter, D.A., 1994. Improved likelihood
#' ratio tests for dispersion models. \emph{International Statistical Review}, pp. 257–274.
#' @examples
#' y <- c("01:00","01:15","01:30","01:45","02:00",
#'        "23:00","23:15","23:30","23:45","00:00")
#' X <- c(rep(0, 5), rep(1, 5))
#' theta <- WH_HHMM_to_rad(y)
#' print(WH_CordeiroPaulaBotter(theta, X))
#' @export
WH_CordeiroPaulaBotter <- function(theta, group) {
    .Call(`_WHcircular_WH_CordeiroPaulaBotter`, theta, group)
}

#' Convert "HH:MM" time-of-day strings to radians
#'
#' Converts times-of-day in "HH:MM" string format (for example, "14:00" for 2:00 PM)
#' to radians.
#' @param input String vector of times in "HH:MM" format.
#' @return A numeric vector of radians.
#' @export
WH_HHMM_to_rad <- function(input) {
    .Call(`_WHcircular_WH_HHMM_to_rad`, input)
}

#' Convert integer times-of-day to radians
#'
#' Converts times-of-day in HHMM integer format (for example, 1400 for 2:00 PM)
#' to radians.
#' @param x Integer vector of times in HHMM format.
#' @return A numeric vector of radians.
#' @export
WH_int_to_rad <- function(x) {
    .Call(`_WHcircular_WH_int_to_rad`, x)
}

#' Convert radians to signed "HH:MM" time differences
#'
#' Converts radians to time-of-day differences in "HH:MM" string format,
#' rounded to the nearest minute. Negative values are prefixed with a minus sign.
#' @param input Numeric vector of radians.
#' @return A string vector of signed time-of-day differences in "HH:MM" format.
#' @export
WH_rad_to_dHHMM <- function(input) {
    .Call(`_WHcircular_WH_rad_to_dHHMM`, input)
}

#' Convert radians to "HH:MM" times
#'
#' Converts radians to times-of-day in "HH:MM" string format,
#' rounded to the nearest minute.
#' @param input Numeric vector of radians.
#' @return A string vector of times-of-day in "HH:MM" format.
#' @export
WH_rad_to_HHMM <- function(input) {
    .Call(`_WHcircular_WH_rad_to_HHMM`, input)
}

#' Circular-linear regression
#'
#' Fits a circular-linear regression¹ model for outcomes in radians.
#' @param y Numeric vector of radians.
#' @param X Numeric matrix of predictors.
#' @param tol Convergence tolerance. Default = 10⁻¹⁰.
#' @return A \code{WH_regfit} list with elements:
#' \itemize{
#'   \item \code{coef}: vector of estimated coefficients, ordered as
#'         κ, μ, \bold{β}.
#'   \item \code{SE}: vector of estimated standard errors, ordered as
#'         κ, μ, \bold{β}.
#'   \item \code{p}: \emph{p}-values of the betas.
#'   \item \code{n}: sample size.
#'   \item \code{loglik}: maximized log-likelihood.
#'   \item \code{vcov}: variance–covariance matrix of the betas.
#' }
#' @references
#' 1. Fisher, N.I. and Lee, A.J., 1992. Regression models for an angular response.
#' \emph{Biometrics}, pp. 665–677.
#' @examples
#' y <- c("01:00","01:15","01:30","01:45","02:00",
#'        "23:00","23:15","23:30","23:45","00:00")
#' X <- c(rep(0, 5), rep(1, 5))
#' theta <- WH_HHMM_to_rad(y)
#' fit <- WH_reg_circlinear(theta, as.matrix(X))
#' print(fit$coef)
#' print(fit$SE)
#' @export
WH_reg_circlinear <- function(y, X, tol = 1e-10) {
    .Call(`_WHcircular_WH_reg_circlinear`, y, X, tol)
}

#' Circular standard deviation
#'
#' Computes the circular standard deviation of a vector of radians.
#' @param theta Numeric vector of radians.
#' @return The circular standard deviation in radians.
#' @examples
#' y <- c("01:00","01:15","01:30","01:45","02:00",
#'        "23:00","23:15","23:30","23:45","00:00")
#' X <- c(rep(0, 5), rep(1, 5))
#' theta <- WH_HHMM_to_rad(y)
#' print(WH_rad_to_HHMM(WH_rad_sd(theta)))
#' @export
WH_rad_sd <- function(theta) {
    .Call(`_WHcircular_WH_rad_sd`, theta)
}

